### ISSUE TITLE
Update the readme for development instructions

### ISSUE THREAD

**Issue by AhsanAyaz** [AhsanAyaz/slides#10]
Acceptance Criteria:
- Update the readme to reflect how to do the following
  - Serve the project (npm run dev)
  - Build the project (npm run build)
  - Deploy the project

Also add the instructions for the project setup (running npm install). Take inspiration from other projects for an amazing readme :)

**Comment by vivekgogi** [comment]
I'd like to work on issue #10 in this repository. Could you please assign it to me?

**Comment by Rasika-exol** [comment]
I'd like to pick this one ,can you please se assign this one to me

**Comment by AhsanAyaz** [comment]
Closed by #17
