### ISSUE TITLE
Move the slides script out of index.html

### ISSUE THREAD

**Issue by AhsanAyaz** [AhsanAyaz/slides#2]
## Current Situation
The javascript code is inside the index.html

## Desired behavior
Move the code to its own javascript file

## Hints

<details><summary>Acceptance Criteria: Expand to see</summary>
<ul>
 <li>Create a new file at the project's root named main.js</li>
 <li>Move the script from index.html to that file</li>
 <li>Import the js file into the index.html via script tag</li>
 <li>Make sure everything works locally (you're able to see the slides)</li>
 <li>Update the gulp-file 'build-talks' task to include the `main.js`</li>
</ul>
</details> 

<img width="717" alt="image" src="https://github.com/AhsanAyaz/slides/assets/9844254/7a2d554d-818b-4ae2-86a6-43222a57865c">

**Comment by Virtual4087** [comment]
can you assign me?

**Comment by Virtual4087** [comment]
Where should i create the js file for the slides?

**Comment by AhsanAyaz** [comment]
Closed by #4
