### ISSUE TITLE
Write a nodeJS script to generate a JSON containing the slides data

### ISSUE THREAD

**Issue by AhsanAyaz** [AhsanAyaz/slides#6]
Current Behavior:
The code in main.js looks at the array within the file to generate slides.

Desired Behavior: 
The code in main.js is supposed to read it from a JSON

Acceptance Criteria:
- A nodejs script that generates that JSON in the folder `data` named `slides.json`

> Note: updating the main.js is not required in this task.

**Comment by AhsanAyaz** [comment]
Assigned to @anttijankeri, @Ramzynco @SvitlanaRybakova

**Comment by rishuxd** [comment]
Hey @AhsanAyaz , Can I work on it?
